baseURL: https://lezuber.github.io
languageCode: en-us
title: Lenz Zuber
theme: "PaperMod"

params:
  homeInfoParams:
    Title: Lenz' Knowledge Garden
    Content: Hi there! On this site, youl'll not only find blog posts, but also all related Evergreen Notes, which I have used to create the posts! To understand what I mean by this, read [Zettelkasten Method](/pages/zettelkasten-method/)

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/lezuber"
    - name: "twitter"
      url: "https://twitter.com/lezuber"
  ShowReadingTime: true
  author: "Lenz Zuber"
  contact: "blog@lezuber.com"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true
  ShowAllPagesInArchive: false

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    # - identifier: categories
    #   name: Categories
    #   url: /categories/
    #   weight: 10
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archive
      name: ðŸŒ³ Evergreens
      url: /tags/evergreen/
      weight: 30
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: 40
